=== juzna/iManaJUZment/data/xml/schema/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://develop.helemik.cz/servisweb/menu"
    xmlns="http://develop.helemik.cz/servisweb/menu"
    elementFormDefault="qualified">

        <xsd:element name="menu">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="menuItem" minOccurs="1" maxOccurs="unbounded" type="menuItemType" />
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>

        <xsd:complexType name="menuItemType">
            <xsd:sequence>
                <xsd:element name="menuItem" minOccurs="0" maxOccurs="unbounded" type="menuItemType" />
            </xsd:sequence>
            <xsd:attribute name="text" type="xsd:string" use="required">
                <xsd:annotation>
                    <xsd:documentation>
                        Caption to be shown in menu item
                    </xsd:documentation>
                </xsd:annotation>
                </xsd:attribute>
            <xsd:attribute name="link" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>
                        Link to serviweb, can be in short form (module;function;ID)
                    </xsd:documentation>
                    </xsd:annotation>
            </xsd:attribute>
            <xsd:attribute name="img">
                <xsd:annotation>
                    <xsd:documentation>
                        Icon to be shown next to menu caption, optional
                    </xsd:documentation>
                </xsd:annotation>
                </xsd:attribute>
            <xsd:attribute name="authModul" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>
                        Module which need to be permited to user to show this menu item, corresponsd with attribute authUkol
                    </xsd:documentation>
                </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="authUkol" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            Job of module to pass authorization to show this menu item
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>

            <xsd:attribute name="show" default="1">
                <xsd:annotation>
                    <xsd:documentation>
                        Whether the item should be displayer (default yes)
                    </xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0" />
                        <xsd:maxInclusive value="1" />
                        </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>

                <xsd:attribute name="moduleSubMenu" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            Name of ServisWeb module, that can generate dynamic submenu items
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>

                <xsd:attribute name="moduleSubMenuParam" type="xsd:string">
                    <xsd:annotation>
                        <xsd:documentation>
                            Parameter to be passed when getting dynamic item by module in attribute moduleSubMenu.
                            </xsd:documentation>
                    </xsd:annotation>
                    </xsd:attribute>
           </xsd:complexType>



</xsd:schema>

=== juzna/iManaJUZment/data/menu.xml
<?xml version="1.0" encoding="windows-1250"?>
<menu  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://develop.helemik.cz/servisweb/menu'
    xsi:schemaLocation='http://develop.helemik.cz/servisweb/menu file:/home/juzna/NetBeansProjects/servisweb/src/menu.xsd'>
	<menuItem text="Zákazníci" link="zakaznik;list" img="Plastic_accounting_cat_Executive.png">
		<menuItem text="Blokování uživatelu" link="ban" img="future_networking_cat_Network_conector_cancel_.png" hide="1" />
	</menuItem>
	<menuItem text="Platba" link="platba;platba" img="Plastic_accounting_cat_Coins.png" hide="1">
		<menuItem text="Pøehled plateb" link="platba;list" />
	</menuItem>
	<menuItem text="AP" link="ap" img="future_networking_cat_Access_point_.png">
		<menuItem text="Skupiny" __link="ap;apgroup" moduleSubMenu="ap" moduleSubMenuParam="groups"/>
		<menuItem text="Stav site" link="nagios" hide="1" />
		<menuItem text="Grafy" link="graf" img="Plastic_accounting_cat_Spread_sheet.png" moduleSubMenu="graf" />
		<menuItem text="Všechny" link="ap?all=1" />
		<menuItem text="Pøidat AP" link="ap-wizard;addForm" />
		<menuItem text="Export do nagiosu" link="nagios;export" hide="1" />
		<menuItem text="Shaping" link="queue" />
	</menuItem>
	<menuItem text="Ostatní" link="pages;;odkazy" img="Plastic_accounting_cat_Barcode.png">
		<menuItem text="Nastaveni" link="nastaveni" hide="1"/>
		<menuItem text="Pøenesená data" link="traffic" hide="1">
			<menuItem text="Celá sí" link="traffic;show;1" />
			<menuItem text="Vytížení sítì" link="traffic;stats" />
		</menuItem>
		<menuItem text="Stav pateøní sítì" link="https://bapr.juzna.cz/nagios3/" target="_blank" />
		<menuItem text="Export do...">
			<menuItem text="radiusu" tooltip="Kompletni nastaveni radiusu" link="radius;nastavKomplet" />
			<menuItem text="pingeru" link="nagios;export_my" />
			<menuItem text="nagiosu" link="nagios;export" />
			<menuItem text="Radius (MacAuth + DHCP) na optice" link="radius;dhcp_optika" />
		</menuItem>
		<menuItem text="Sítové funkce" link="net">
			<menuItem text="Ping" link="net;ping" />
		</menuItem>
		<menuItem text="Jine">
			<menuItem text="Akce na pozadi" link="servisweb;deferlist" />
		</menuItem>
		<menuItem text="Tabulky">
			<menuItem text="Seznam" link="tables;list" />
			<menuItem text="Wizard" link="tables;wizard" />
		</menuItem>
		<menuItem text="Napoveda" link="napoveda" />
	</menuItem>
</menu>
