=== juzna/iManaJUZment/data/xml/schema/tables.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://develop.helemik.cz/tables"
    xmlns="http://develop.helemik.cz/tables"
    elementFormDefault="qualified">

    <xsd:element name="table">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice id="db" minOccurs="0">
                    <xsd:element name="db" type="xsd:token" />
                    <xsd:element name="database" type="xsd:token" />
                </xsd:choice>
                <xsd:element name="title" type="xsd:string" minOccurs="0" />
                <xsd:choice id="params" minOccurs="0">
                    <xsd:element name="params" type="paramsType" />
                    <xsd:element name="parameters" type="paramsType" />
                </xsd:choice>
                <xsd:element name="preface" minOccurs="0" maxOccurs="1" type="prefaceType" />
                <xsd:element name="sql" type="xsd:string" />
                <xsd:element name="fields" type="fieldsType" minOccurs="0" maxOccurs="1"   />
                <xsd:element name="empty" type="xsd:string" minOccurs="0" maxOccurs="1"  />
                <xsd:element name="edit" type="editType" minOccurs="0" maxOccurs="1" />
                <xsd:element name="change" type="changeType" minOccurs="0" maxOccurs="1" />
                <xsd:element name="foot" type="html" minOccurs="0" maxOccurs="1"  />
                <xsd:element name="menu" type="menuType" minOccurs="0" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" use="required" type="xsd:token" />
            <xsd:attribute name="export" use="optional" type="xsd:int" />
            <xsd:attribute name="height" type="xsd:int" use="optional" />
            <xsd:attribute name="template" type="xsd:token">
                <xsd:annotation>
                    <xsd:documentation>
                        ID sablony, ktera se pouzije jako vzor. Pak se zde uvede pouze rozdil oproti teto sablone
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="paramsType">
        <xsd:annotation>
            <xsd:documentation xml:lang="cs">
                Seznam parametru, ktere je potreba zadat pro vytvoreni tablky
            </xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="param" type="paramType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="paramType">
        <xsd:attribute name="name" type="xsd:token" use="required" />
        <xsd:attribute name="type" type="xsd:token" />
        <xsd:attribute name="title" type="xsd:string" />
        <xsd:attribute name="sql" type="xsd:string" />
        <xsd:attribute name="format" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="fieldsType">
        <xsd:sequence>
            <xsd:element name="field" type="fieldType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="index" type="xsd:token">
            <xsd:annotation>
                <xsd:documentation xml:lang="cs">
                Sloupec z databaze, ktery je unikatnim indexem pro danou tabulku
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="sort" type="xsd:token">
            <xsd:annotation>
                <xsd:documentation>
                Sloupec, podle ktereho se ma defaultne radit vystup
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="fieldType">
        <xsd:choice>
            <xsd:element name="filter" type="filterType" minOccurs="0" maxOccurs="1" />
            <xsd:element name="content" type="xsd:string" minOccurs="0" maxOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:token" use="required" />
        <xsd:attribute name="show" type="bool" use="required" />
        <xsd:attribute name="variable" type="xsd:token" />
        <xsd:attribute name="title" type="xsd:string" />
        <xsd:attribute name="width" type="xsd:int" />
        <xsd:attribute name="icon" type="xsd:token">
            <xsd:annotation>
                <xsd:documentation>
                    Kod ikonky pro danou bunku tabulky
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="href" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>
                    Odkaz kam povede ikonka v dane bunce
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="sortBy" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>
                    Seznam sloupcu, podle kterych se ma seradit vysledek pri tomto kliku (vlozeno primo do SQL dotazu do ORDER BY)
                </xsd:documentation>

            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="default" type="xsd:string" />
        <xsd:attribute name="format" type="xsd:string" />
        <xsd:attribute name="window" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>
                    Zda se ma dany odkaz zobrazovat ve vlastnim oknde
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="bool">
        <xsd:restriction base="xsd:int">
            <xsd:enumeration value="0" />
            <xsd:enumeration value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="filterType">
        <xsd:sequence>
            <xsd:element name="option" type="filterOptionType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="type" type="filterTypeType" use="required" />
    </xsd:complexType>

    <xsd:complexType name="filterOptionType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="value" type="xsd:string"  use="required" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="filterTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="enum" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="editType">
        <xsd:sequence>
            <xsd:element name="default" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="name" type="xsd:token" use="required" />
                    <xsd:attribute name="value" type="xsd:string" />
                    <xsd:attribute name="variable" type="xsd:token" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="type" type="editTypeType" use="required" />
        <xsd:attribute name="form" type="xsd:token">
            <xsd:annotation>
                <xsd:documentation>
                Pokud je type=editform, pak oznacuje jmeno formulare pro editaci
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="edit" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>
                URL adresa odkazujici na editaci konkretniho prvku tabulky
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="add" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation>
                URL adresa odkazujici na pridani noveho prvku do teto tabulky
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="delete" type="xsd:string" />

    </xsd:complexType>

    <xsd:simpleType name="editTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="link" />
            <xsd:enumeration value="editform" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="changeType">
        <xsd:attribute name="show" type="bool" />
        <xsd:attribute name="table" type="xsd:token" use="required" />
        <xsd:attribute name="params" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="html" mixed="true">
        <xsd:sequence>
            <xsd:any minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="menuType">
        <xsd:sequence>
            <xsd:element name="item" type="menuItemType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="menuItemType">
        <xsd:attribute name="title" type="xsd:string" use="required" />
        <xsd:attribute name="tooltip" type="xsd:string" />
        <xsd:attribute name="onclick" type="xsd:string" />
        <xsd:attribute name="href" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="prefaceType" mixed="true">
        <xsd:sequence>
            <xsd:element name="sql" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== juzna/iManaJUZment/app/APModule/tables/group.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap-group">
	<db>data</db>
	<sql>select * from `APgroup`</sql>
	<fields index="ID">
		<field name="ID" title="ID" show="1" variable="ID" />
		<field name="Nazev" title="Nazev" show="1" variable="Nazev" />
		<field name="Popis" title="Popis" show="1" variable="Popis" />
		<field name="notification_interval" title="notification_interval" show="0" variable="notification_interval" />
		<field name="notification_period" title="notification_period" show="0" variable="notification_period" />
		<field name="contact" title="contact" show="0" variable="contact" />
		<field name="trouble_user" title="trouble_user" show="0" variable="trouble_user" />
		<field name="trouble_group" title="trouble_group" show="0" variable="trouble_group" />
		<field name="defaultIP" title="Vychozi IP" show="0" variable="defaultIP" />
	</fields>
	<edit type="editform" form="APgroup" />	
	<foot></foot>
</table>

=== juzna/iManaJUZment/app/APModule/tables/swif.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap-swif" export="1">
	<db>data</db>
	<title>Softwarova rozhrani</title>
	<params>
		<param name="ap" type="int" title="Sitovy prvek" sql="SELECT id, nazev FROM AP" />
	</params>
	<source type="d:model" model="AP" id="ap" property="APSwIf" />
	<fields index="ID">
		<field name="id" variable="ID" title="#" show="1"/>
		<field name="interface" variable="interface" title="Rozhrani"  show="1"/>
		<field name="type" variable="typ" title="Typ"  show="1"/>
		<field name="comment" variable="popis" title="Popis"  show="1"/>
		<field name="ssid" variable="ssid" title="SSID"  show="1"/>
		<field name="frekvence" variable="frekvence" title="Frekvence"  show="1"/>
		<field name="enc" title="Sifrovani" show="1">
			<content>
				<COND EXP="$enc">{$enc}: {$enc_klic}</COND>
			</content>
		</field>
		<field name="graph" title="Graf vytizeni" show="0" >
			<content>
				{!graf('if-bytes', "$AP-$interface", true)}
			</content>
		</field>
	</fields>
	<edit type="editform" form="APswif">
		<default name="AP" variable="ap" />
	</edit>
</table>

=== juzna/iManaJUZment/app/APModule/tables/list.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap:list" name="ap-list" export="1" height="500">
    <title>Seznam sitovych prvku</title>
    <source type="d:table">AP</source>
    <fields index="ID" sort="nazev">
        <field width="20" name="id" show="1" variable="ID" title="#" />
        <field width="250" name="name" title="Nazev" show="1" icon="details" href="ap;detail;{$ID}" variable="name" />
        <field width="120" name="comment" title="Popis" variable="description" show="0" />
        <field width="30" name="mode" title="Mod" variable="mode" show="0">
            <filter type="enum">
                <option value="bridge">Bridge</option>
                <option value="route">Router</option>
                <option value="NAT">NAT</option>
                <option value="other">Jine</option>
            </filter>
        </field>
        <field width="100" name="os" title="Operacni system" show="0">
          <content><![CDATA[ {$ID} {$name}, {$mode} ]]></content>
        </field>
    </fields>
</table>

=== juzna/iManaJUZment/app/APModule/tables/vlan.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://develop.helemik.cz/tables"
       xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
	id="ap-vlan">
	<db>data</db>
	<title>VLANy</title>
	<params>
		<param name="ap" type="int" title="Sitovy prvek" />
	</params>
	<sql>select * from `APPortVlan` where `AP`={$ap}</sql>
	<fields index="ID">
		<field name="ID" title="ID" show="0" variable="ID" />
		<field name="AP" title="AP" show="0" variable="AP" />
		<field name="port" title="port" show="1" variable="port" />
		<field name="vlan" title="vlan" show="1" variable="vlan" />
		<field name="tagged" title="tagged" show="1" variable="tagged" />
		<field name="pvid" title="pvid" show="1" variable="pvid" />
	</fields>
	<edit type="editform" form="APvlan">
		<default name="AP" variable="ap" />
	</edit>
</table>

=== juzna/iManaJUZment/app/APModule/tables/ips.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap-ips" export="1">
	<params>
		<param name="ap" type="int" title="Sitovy prvek" sql="SELECT ID, Nazev FROM AP" />
	</params>
	<title>IP adresy</title>
	<source type="d:model" model="AP" id="ap" property="APIP" />
	<fields index="ID">
		<field name="id" variable="ID" title="#" show="1"/>
		<field name="ip" title="IP" show="1">
			<content>{$ip}/{$netmask}</content>
		</field>
		<field name="interface" variable="interface" title="Rozhrani" show="1"/>
		<field name="comment" variable="comment" title="Popis" show="1"/>
		<field name="flags" title="Priznaky" show="1">
			<content>
				{= $not_real ? 'Tato IP zde fyzicky neni' : ''}
				{= $no_people ? 'Neprirazovat zakazniky' : ''}
			</content>
		</field>
	</fields>
	<edit type="editform" form="APIP">
        <default name="AP" variable="ap" />
    </edit>
	<menu>
		<item title="Ping" onclick="ServisWeb.ping(row.IP);" />
		<item title="Otevrit admin" onclick="window.open('http://' + row.IP + '/', '_blank');" />
	</menu>
</table>

=== juzna/iManaJUZment/app/APModule/tables/zakaznici.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap-zakaznici">
	<db>data</db>
	<title>Zákazníci na tomto AP</title>
	<params>
		<param name="ap" type="int" title="AP " sql="SELECT ID,Nazev,popis FROM AP" />
	</params>
	<sql>SELECT Zakaznici.*, ZakaznikAdresa.*, ZakazniciIP.ID, IP, AP, APif, AP2, AP2if, MAC 
		FROM `ZakazniciIP` LEFT JOIN `Zakaznici` ON Zakaznici.PorCis=ZakazniciIP.PorCis 
		LEFT JOIN `ZakaznikAdresa` ON ZakaznikAdresa.PorCis=Zakaznici.PorCis
		WHERE AP='{$ap}' OR AP2='{$ap}'
		GROUP BY `ZakazniciIP`.ID ORDER BY ZakaznikAdresa.Prijmeni</sql>
	<fields index="ID">
		<field name="ID" variable="ID" title="#" show="0"/>
		<field name="PorCis" variable="PorCis" title="Cislo smlouvy" show="1" />
		<field name="zakaznik" title="Zakaznik" show="1" icon="details" href="zakaznik;detail;{$PorCis}">
			<content>{$Jmeno} {$Prijmeni}</content>
		</field>
		<field name="Skupina" variable="Skupina" title="Skupina" show="0"/>
		<field name="tarif" variable="tarif" title="tarif"  show="0" />
		<field name="tarifSpec" variable="tarifSpec" title="Speciální tarif" show="0" />
		<field name="IP" variable="IP" title="IP adresa"  show="1"/>
		<field name="netmask" variable="netmask" title="Podmaska" show="0" />
		<field name="IPold" variable="IPold" title="Ip stará" show="0" />
		<field name="IPverejne" variable="IPverejne" title="IP veøejné" show="0" />
		<field name="verejmask" variable="verejmask" title="Veøejná maska" show="0" />
		<field name="MAC" variable="MAC" title="MAC" show="0" />
		<field name="VisibleMAC" variable="VisibleMAC" title="Viditelná MAC" show="0" />
		<field name="auto" variable="auto" title="auto" show="0" />
		<field name="adresa" variable="adresa" title="adresa" show="0" />
		<field name="Ulice" variable="Ulice" title="Ulice" show="0" />
		<field name="CisloPopisne" variable="CisloPopisne" title="Cislo popisne" show="0" />
		<field name="Mesto" variable="Mesto" title="Mesto" show="0" />
		<field name="PSC" variable="PSC" title="PSÈ" show="0" />
		<field name="AP" variable="AP" title="AP"  show="1"/>
		<field name="APif" variable="APif" title="AP Interface" show="1" />
		<field name="posX" variable="posX" title="pozice X" show="0" />
		<field name="posY" variable="posY" title="pozice Y" show="0" />
		<field name="AP2" variable="AP2" title="AP2"  show="1"/>
		<field name="AP2if" variable="AP2if" title="AP2 interface" show="1" />
		<field name="Popis" variable="Popis" title="Popis" show="0" />
		<field name="wep_use" variable="wep_use" title="Šifrování WEP" show="0" />
		<field name="wep_key" variable="wep_key" title="Wep klíè" show="0" />
		<field name="NAT" variable="NAT" title="NAT" show="0" />
		<field name="voipHlas" variable="voipHlas" title="VoIP Telefon" show="0" />
		<field name="voipData" variable="voipData" title="VoIP Fax" show="0" />
		<field name="vlastniRychlost" variable="vlastniRychlost" title="Vlasní rychlost" show="0" />
		<field name="txmin" variable="txmin" title="Odesílání minimální" show="0" />
		<field name="rxmin" variable="rxmin" title="Pøíjem minimální" show="0" />
		<field name="rx" variable="rx" title="prijmani" show="0" />
		<field name="tx" variable="tx" title="odesilani" show="0" />
		<field name="rxburst" variable="rxburst" title="Pøíjem burst" show="0" />
		<field name="txburst" variable="txburst" title="Odesílání burst" show="0" />
		<field name="rxbursttresh" variable="rxbursttresh" title="Pøíjem burst tresh" show="0" />
		<field name="txbursttresh" variable="txbursttresh" title="Pøíjem burst trush" show="0" />
		<field name="rxburstime" variable="rxburstime" title="Pøíjem burst time" show="0" />
		<field name="txburstime" variable="txburstime" title="Pøíjem burst time" show="0" />
		<field name="priority" variable="priority" title="Priority" show="0" />
		<field name="APIP" variable="APIP" title="APIP" show="0" />
		<field name="APMAC" variable="APMAC" title="APMAC" show="0" />
		<field name="allowDHCP" variable="allowDHCP" title="Povolení DHCP" show="0" />
		<field name="nazev" variable="nazev" title="Název"  show="1"/>
		<field name="Popis" variable="Popis" title="Popis"  show="0" />
		<field name="Mode" variable="Mode" title="Mód" show="0"/>
		<field name="APhw" variable="APhw" title="AP hw"  show="0" />
		<field name="parent" variable="parent" title="Rodiè:)" show="0" />
		<field name="parentif" variable="parentif" title="Rodiè Interface:)" show="0"/>
		<field name="posX" variable="posX" title="pozice X" show="0" />
		<field name="posY" variable="posY" title="pozice Y" show="0" />
		<field width="160" name="adress" title="Adresa" sortBy="Ulice, CisloPopisne, Mesto" show="1">
			<content>
				<![CDATA[<COND EXP="$Mesto">{$Ulice} {$CisloPopisne}, {$Mesto}</COND>]]>
			</content>
		</field>
		<field name="Typ" variable="Typ" title="Typ"  show="1"/>
		<field name="img" variable="img" title="Image" show="0" />
		<field name="SNMP" variable="SMMP" title="SNMP" show="0" />
		<field name="Comunity" variable="Comunity" title="Komunita" show="0" />
		<field name="Realm" variable="Realm" title="Realm" show="0" />
		<field name="username" variable="username" title="Uživatel" show="0" />
		<field name="password" variable="password" title="heslo" show="0" />
		<field name="os" variable="os" title="OS" show="0" />
		<field name="osVerze" variable="osVerze" title="Verze OS" show="0" />
		<field name="igcnt" variable="igcnt" title="igcnt" show="0"/>
		<field name="group" variable="group" title="Skupina" show="0" />
		<field name="ipmac_def" variable="ipmac_def" title="IP MAC" show="0"/>
		<field name="show_in_nagios" variable="show_in_nagios" title="Nagios" show="0" />
		<field name="bez_adresy" variable="bez_adresy" title="Bez adresy" show="0" />
		<field name="wep_use" variable="wep_use" title="Šifrování WEP" show="0" />
		<field name="wep_key" variable="wep_key" title="Wep klíè" show="0" />
		<field name="fingerprint" variable="fingerprint" title="fingerprint" show="0" />
	</fields>
</table>

=== juzna/iManaJUZment/app/APModule/tables/port.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://develop.helemik.cz/tables"
       xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
	id="ap-port">
	<db>data</db>
	<title>Porty switche</title>
	<params>
		<param name="ap" type="int" title="Sitovy prvek" />
	</params>
	<source type="d:model" model="AP" id="ap" property="APPort" />
	<fields index="ID">
		<field name="ID" title="ID" show="0" variable="ID" />
		<field name="AP" title="AP" show="0" variable="AP" />
		<field name="port" title="port" show="1" variable="port" />
		<field name="typ" title="typ" show="1" variable="typ" />
		<field name="PorCis" title="PorCis" show="0" variable="PorCis" />
		<field name="zakaznik" title="Zakaznik" show="1" variable="PorCis" format="zakaznik" icon="details" href="zakaznik;detail;{$PorCis}" />
		<field name="odbernaAdresa" title="odbernaAdresa" show="1" variable="odbernaAdresa" />
		<field name="cisloVchodu" title="cisloVchodu" show="1" variable="cisloVchodu" />
		<field name="cislobytu" title="cislobytu" show="1" variable="cislobytu" />
		<field name="connectedTo" title="connectedTo" show="1" variable="connectedTo" format="AP" />
		<field name="connectedInterface" title="connectedInterface" show="1" variable="connectedInterface" />
		<field name="connectedPort" title="connectedPort" show="1" variable="connectedPort" />
		<field name="isUplink" title="isUplink" show="1" variable="isUplink" format="bool" />
		<field name="popis" title="popis" show="1" variable="popis" />
	</fields>
	<edit type="editform" form="APPort">
		<default name="AP" variable="ap" />
	</edit>
</table>

=== juzna/iManaJUZment/app/APModule/tables/hardware.xml
<?xml version="1.0" encoding="windows-1250"?>
<table xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://develop.helemik.cz/tables"
    xsi:schemaLocation="http://develop.helemik.cz/tables tables.xsd"
    id="ap-hardware">
	<db>data</db>
	<params>
		<param name="hw" type="int" title="Hardware interface" sql="SELECT ID FROM APhw" />
	</params>
	<preface><![CDATA[<h3>Hardware interface</h3>]]></preface>
	<sql>SELECT * FROM APhwif WHERE APhw={$hw}</sql>
	<fields index="ID">
		<field name="id" variable="ID" title="#" show="1" />
		<field name="name" variable="nazev" title="Rozhrani" show="1" />
		<field name="MAC" variable="MAC" title="MAC" show="1"  />
		<field name="comment" variable="popis" title="Popis" show="1" />
		<field name="type" variable="Typ" title="Typ" show="1" />
		<field name="net" variable="net" title="net" show="0" />
		<field name="APhw" variable="APhw" title="APhw" show="0" />
	</fields>
</table>
